-- ISSUE #1: LARGE AMOUNTS OF MISSINGNESS IN CATEGORYCODE, EVEN WHEN CATEGORY IS NON-NULL. 49% OF BRANDS WITH A NON-NULL CATEGORY HAVE A MISSING CATEGORY CODE. 13% OF RECORDS HAVE A MISSIN CATEGORY VALUE.
select category, categoryCode, count(*) from `sandbox.brands` group by 1,2 order by 1,2;

-- ISSUE #2: BRANDCODE CONTAINS NULLS, HARDCODED BLANK STRINGS, TRUE DUPES, AND PROBABLE CONTEXTUAL DUPES (I.E. CHESTER'S VERSUS CHESTERS). THIS COLUMN WOULD BE VERY DIFFICULT TO USE IN PRACTICE. I WOULD SUGGEST CONVERTING TO A NUMERIC ID INSTEAD OF WHAT APPEARS TO BE MANUALLY ASSIGNED VALUES.
select brandCode, count(*) from `sandbox.brands` group by 1 order by 2 desc;

-- ISSUE #3: BARCODE IS NON UNIQUE (HOWEVER, DEPENDING ON SUBJECT MATTER EXPERTISE, THIS COULD BE ACCEPTABLE, AS IT IS UNIQUE ON BARCODE X BRANDCODE).
select barcode, count(*) from `sandbox.brands` group by 1 order by 2 desc;

-- ISSUE #4: TOP BRAND IS NOT TRUE BOOL, AND IS OFTEN NULL. TOP BRAND SHOULD BE TRUE / FALSE (ALTHOUGH 1/0 COULD BE FINE DEPENDING ON STYLE GUIDE), AND IS 52% NULL, NEGATING ITS UTILITY AS AN INDICIATOR.
select topBrand, count(*) from `sandbox.brands` group by 1 order by 2 desc;

-- STYLE ISSUE: NAME FIELD IS NOT CASE OR SPECIAL CHARACTER STANDARDIZED.  FOR EASE OF USE, THIS FIELD SHOULD BE EITHER ALL UPPER OR LOWER CASE, AND SPECIAL CHARACTERS SHOULD BE STRIPPED.
select name, count(*) from `sandbox.brands` group by 1 order by 2 desc;

-- NON-ISSUE: PRIMARY KEY IS UNIQUE.
select _id, count(*) from `sandbox.brands` group by 1 having count(*) > 1 order by 2 desc;